Move services out from docker containers for development
rittaschool/ritta-server pull request #114
Opened 2022-06-29 19:34 UTC by kymppi

2022-06-30 20:54 UTC, kymppi commented
Currently not done services are: messages, core

2022-07-10 14:16 UTC, raikasdev requested changes
Should the files in environments/local/docker/grafana/publish/ be there?

2022-07-10 16:03 UTC, kymppi reviewed
Those files were there before, just moved to a new location. Let's let them be so we wont break grafana, can be cleaned later if they're unnesessary.

2022-07-10 16:12 UTC, raikasdev approved these changes

2022-07-10 16:14 UTC, merged